iter9
theheadmen/urlShort pull request #11
Opened 2023-12-26 15:05 UTC by theheadmen

2023-12-28 16:10 UTC, bambruysk requested changes
Нужно дороаботать выделив отдельные пакеты для харанения урлов в памяти и в файле

2023-12-28 16:10 UTC, bambruysk commented on cmd/logger/logger.go
> +// Никакой код навыка, кроме функции InitLogger, не должен модифицировать эту переменную.
навык)

2023-12-28 16:10 UTC, bambruysk commented on cmd/serverconfig/serverconfig.go
> +				logger.Log.Fatal("Failed unmarshal data", zap.Error(err))
не стоит фаталить тут - лучше вернгуть ошибку. Например верхнеуровневый код может решить что делать, прочитать повторно, выбрать другой файл и тд. Предоставим ему такую возможность

2023-12-28 16:10 UTC, bambruysk commented on cmd/shortener/main_test.go
> +	} else {
else - лишняя

2023-12-28 16:10 UTC, bambruysk commented on cmd/shortener/main.go
> +	}
слишком много на себя берет хендлер - лучше бы вынести это в отдельный метод storage

2023-12-28 16:10 UTC, bambruysk commented on cmd/serverconfig/serverconfig.go
> +}
Лучше не приделывать методы сохранения к моделям данных.
Создайте структуру FileStorage и пусть она реализует интерфейс репозитория
Тме более что странно, это все находится в serverconfig

То есть у вас должен быть объект который умеет хранить 

type Storager interface {
     SaveURL( url URL) error
     GertURL(id string) (URL,error)  
}

что-то наподобии такого

2023-12-28 16:10 UTC, bambruysk commented on cmd/serverconfig/serverconfig.go
> +// Load читает настройки из файла fname.
Настройки или URL?

2023-12-29 05:02 UTC, theheadmen commented
@bambruysk готово, вынес в Storager

2023-12-29 17:01 UTC, bambruysk approved these changes
Принято ) но нужно дорабоать будет репозиторий

2023-12-29 17:01 UTC, bambruysk commented on cmd/storager/storager.go
> +	}
мы стремимся избавляться от else и лишних вложенностей ( это не моя заморочка, это общегошное)

для этого используется ранний выход

```
	file, err := os.Open(storager.filePath)
	if err != nil {
		if os.IsNotExist(err) {
			logger.Log.Debug("File does not exist. Leaving SavedURLs empty.")
		} else {
			logger.Log.Error("Failed to open file", zap.Error(err))
		}
                return err // да да пусть метод возвращает ошибку
	} 
	
      defer file.Close()
      //  и далее по коду 
```

2023-12-29 17:01 UTC, bambruysk commented on cmd/storager/storager.go
> +func (storager *Storager) StorageURL(shortURL string, originalURL string) {
Имя функции должно строится по принципу глаголОбъект то есть StoreURL или SaveURL

2023-12-29 17:01 UTC, bambruysk commented on cmd/storager/storager.go
> +	if !ok {
if ok {
    return 
}

2023-12-29 17:01 UTC, bambruysk commented on cmd/shortener/main.go
> +	dataStore := NewServerDataStore(configStore, storager)
Не отвественость сервера управлять storage -  лучше передать в него снаружи)

2023-12-29 17:01 UTC, bambruysk commented on cmd/shortener/main.go
> +	dataStore.storager.StorageURL(shortURL, req.URL)
Здесь явно вызывается метод с файлами - а хотелось бы чтобы у них были одни и те же методы

2023-12-29 17:43 UTC, theheadmen commented on cmd/shortener/main.go
> +	dataStore.storager.StorageURL(shortURL, req.URL)
Ничего не понял - у кого у "них" и что должно быть одинаковым?

2023-12-29 18:05 UTC, theheadmen commented
@bambruysk за исключением непонятого мною комментария - готово

2024-01-12 14:36 UTC, merged