Iter13
theheadmen/urlShort pull request #15
Opened 2024-01-17 12:08 UTC by theheadmen

2024-01-21 07:04 UTC, bambruysk requested changes
Нужно поработать с контекстами для БД

2024-01-21 07:04 UTC, bambruysk commented on cmd/storager/storager.go
> +	// если у нас уже все и так было вставлено, нам не нужно ничего сохранять
слишком долгий путь, и к тому же нет гарантии что там паралельно кто-то что-то не записывает. Лучше решить это на уровне sql или хранилища в памяти

2024-01-21 07:04 UTC, bambruysk commented on cmd/dbconnector/dbconnector.go
> +}
тестовые штуки лучше создавать в файлах _test.go

2024-01-21 07:04 UTC, bambruysk commented on cmd/dbconnector/dbconnector.go
> +package dbconnector
Этот пакет ( как и другие) должен быть в папке internal или pkg, ( лучше в internal) - в cmd кладем только пакеты предназначенные для сборки, то есть содержащие  main

2024-01-21 07:04 UTC, bambruysk commented on cmd/dbconnector/dbconnector.go
> +func NewDBConnector(psqlInfo string) *DBConnector {
Этот конструктор стоит научить возвращать ошибку и возвращать ее если что-то пошло не так

2024-01-21 07:04 UTC, bambruysk commented on cmd/dbconnector/dbconnector.go
> +	IsAlive bool
IsAlive - не нужен, Если нужно проверить коннект лучге использовать Ping

2024-01-21 07:04 UTC, bambruysk commented on cmd/dbconnector/dbconnector.go
> +	_, err = db.Exec(sqlStatement)
Здесь и в других местх идет поход в БД без контекста. Что неправильно, так как в случае отказа БД запрос к ней может навсегда повиснуть и вызов Exec заблокируется. 
Контекст нужно взять из r.Context() запроса HTTP

2024-01-21 07:04 UTC, bambruysk commented on cmd/dbconnector/dbconnector.go
> +		logger.Log.Fatal("Failed to initiate transaction for DB", zap.Error(err))
не надо фаталить все приложение из за неудачного запроса - просто верните ошибку

2024-01-21 07:04 UTC, bambruysk commented on cmd/dbconnector/dbconnector.go
> +		logger.Log.Fatal("Failed to prepate query for DB", zap.Error(err))
Здесь тоже надо вернуть ошибку и не забыть Rollback

2024-01-21 10:44 UTC, theheadmen commented on cmd/storager/storager.go
> +	// если у нас уже все и так было вставлено, нам не нужно ничего сохранять
1 - зачем каждый раз посылать запрос, если я уже знаю что по такому URL что-то есть в базе/файле?
Удаления нет на данный момент, если при запуске сервера мы прочитали (без разницы откуда), то значит оно никуда не денется

2 - Так ведь это уже хранилище в памяти, я ведь проверяю по тому что есть в storager

2024-01-21 10:52 UTC, theheadmen commented on cmd/dbconnector/dbconnector.go
> +	IsAlive bool
Почему?
Если на старте мы не смогли надежно подключиться к БД, значит мы не смогли как минимум подтянуть данные оттуда и ради безопасности стоит работать с другими хранилищами

Если у нас изначально было успешное подключение, то имеет смысл перед запросом проверять соединение, да
Но и здесь isAlive не теряет смысла, потому что мы все равно должны знать был ли жив сервер изначально

2024-01-21 12:26 UTC, theheadmen commented
@bambruysk перенес пакеты в internal, добавил контекст, убрал isAlive (проверяю nil)

2024-01-23 16:38 UTC, bambruysk requested changes
Из main.go нужно вынести ServerDataStore ( в пакет api например) и прочее что не относится ко всему приложению

по факту в main.go должегн быть выскоуровневый код, в котором мы собираем осталььные компоненты приложения

2024-01-23 16:38 UTC, bambruysk commented on cmd/shortener/main.go
> +	dbConnector, _ := dbconnector.NewDBConnector(ctx, configStore.FlagDB)
не надо игнорировать ошибку, можно добавить тут панику или log.Fatal

2024-01-23 16:38 UTC, bambruysk commented on cmd/shortener/main.go
> +	storager.ReadAllData(ctx)
это можно прям внутрь конструктора storrager засунуть

2024-01-23 18:11 UTC, theheadmen commented
@bambruysk перенес функционал в отдельный пакет serverapi

2024-01-26 06:40 UTC, theheadmen commented
@bambruysk вежливое напоминание про то что я все еще надеюсь на апрув)

2024-01-26 15:49 UTC, bambruysk approved these changes
принято, но замечание лучше исправить

2024-01-26 15:49 UTC, bambruysk commented on internal/serverapi/serverapi.go
> +	}
это должно задаваться в тестах
Зачем мы делаем эти вычисления при каждом запросе?

2024-01-27 14:55 UTC, theheadmen commented on internal/serverapi/serverapi.go
> +	}
@bambruysk хорошо, поправлю в следующих инкрементах

Не забудьте, пожалуйста, апрувнуть и в практикуме!

2024-01-27 14:55 UTC, merged