Iter15
theheadmen/urlShort pull request #17
Opened 2024-01-31 15:03 UTC by theheadmen

2024-02-05 10:30 UTC, bambruysk requested changes
В задании указано - что удаление должно быть асинхронным, тут удаление синхронное то есть ответ отправляется пользователю после удаления

Оптимально, запускать отложенную горутину, которая будет писать savedurl и userID в какой-то канал, а с другой стороны по мере необходимости/ возможности эти urls считывать и удалять из БД

2024-02-05 10:30 UTC, bambruysk commented on internal/dbconnector/dbconnector.go
> +			return emptyURLs, err
можно просто nil вернуть было бы, dvtcnj enptyUrls

2024-02-05 10:30 UTC, bambruysk commented on internal/dbconnector/dbconnector.go
> +		logger.Log.Info("Failed to prepare the statement: ", zap.Error(err))
Уровень логгирования для ошибок лучше ставить Error

2024-02-05 10:30 UTC, bambruysk commented on internal/serverapi/serverapi.go
> +	isAlreadyStored := dataStore.storager.StoreURL(r.Context(), shortURL, req.URL, userID)
у метода довольно много параметров уже, лучше скомбигировать их в структуру, чтобы проще добавлять было.

2024-02-05 10:30 UTC, bambruysk commented on internal/serverapi/serverapi.go
> +		} else {
здесь лучше на return заменить

2024-02-05 10:30 UTC, bambruysk commented on internal/serverapi/serverapi.go
> +	if err != nil || !token.Valid {
если токен невалидный то какая вернется ошибка? nil - значит пользователи функции посчитают что он валидный и можно его использовать - лучше здесь вернуть ошибку

2024-02-05 10:30 UTC, bambruysk commented on internal/storage/database/database_storager.go
> +	storager.DB.InsertSavedURLBatch(ctx, []models.SavedURL{savedURL}, userID)
если произошла ошибка при вставке в базу, то кэш невалиден уже, так как в него вписали, а в БД нет

2024-02-05 10:30 UTC, bambruysk commented on internal/storage/database/database_storager.go
> +	URLMap      map[storage.URLMapKey]models.SavedURL
при работе с БД в данном случае лучше отказаться от кэша, так как слишком много сложностей возникает, которые не требовались в задании

2024-02-05 15:35 UTC, theheadmen commented on internal/serverapi/serverapi.go
> +		} else {
Не понял что именно тут должно быть return - не next.ServeHTTP(w, r) ведь?

2024-02-05 16:48 UTC, theheadmen commented
@bambruysk готово

Разве что я не понял что именно вы просите поправить относительно return + "next.ServeHTTP(w, r)", поэтому не изменял ничего

2024-02-07 14:48 UTC, bambruysk approved these changes
Принято

2024-02-07 14:48 UTC, bambruysk commented on internal/storage/database/database_storager.go
> +		return models.SavedURL{}, false, nil
Если задать ошибку типа ErrNotFound - то можно избавиться от флага

2024-03-23 11:27 UTC, merged