iter20
theheadmen/urlShort pull request #21
Opened 2024-04-07 11:28 UTC by theheadmen

2024-04-11 21:13 UTC, bambruysk requested changes
Нужно немноо порефачить

2024-04-11 21:13 UTC, bambruysk commented on cmd/staticlint/main.go
> +		return nil, nil
слишком глубокая вложенность лучше разбить на несколько функций и использовать ранний выход

fe 
```
fun, ok := call.Fun.(*ast.SelectorExpr)
 if !ok {
    return true
}
```

2024-04-11 21:13 UTC, bambruysk commented on cmd/staticlint/main.go
> +		return nil, nil
а линтеры прогонялись на проекте?

2024-04-12 07:15 UTC, theheadmen commented on cmd/staticlint/main.go
> +		return nil, nil
Да, из-за того что у меня автоматом в VS Code идет пачка всяких проверок (я уже не помню, так было указано в первых заданиях по "как установить GO" или я сам нашел) - которые явно шире чем наш ограниченный набор здесь, для задания - прогон маленькой самописной проверки конечно же проходит без проблем

2024-04-16 07:25 UTC, bambruysk reviewed
Принято

2024-04-18 13:37 UTC, merged